steps:
      - name: Depoyu Cek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # --- YENİ EKLENECEK KISIM (Dedektif) ---
      - name: Dosyalari Listele (DEBUG)
        run: ls -R
      # ---------------------------------------

      - name: Kutuphaneleri Yukle
        run: |
          # Burada tırnak işaretine dikkat ediyoruz ama isim yanlışsa yine patlar
          pip install -r "Jobverse Automated/requirements.txt"

      - name: Analizi Calistir
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python "Jobverse Automated/main_analysis_github.py"
