name: Haftalik Jobverse Analizi

on:
  schedule:
    - cron: '0 9 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Cek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # DÜZELTME: Adresin başına "Resources/" ekledik.
      - name: Kutuphaneleri Yukle
        run: |
          pip install -r "Resources/Jobverse Automated/requirements.txt"

      # DÜZELTME: Python dosyasının yolunu da güncelledik.
      - name: Analizi Calistir
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python "Resources/Jobverse Automated/main_analysis_github.py"
